### ISSUE TITLE
we still don't delete lost issues

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#229]
I see this error in https://github.com/zerocracy/judges-action/actions/runs/10244197405/job/28336753051

```
Octokit::NotFound: GET https://api.github.com/repositories/728758275/issues/161/timeline?per_page=100: 404 - Not Found // See: https://docs.github.com/rest/issues/timeline#list-timeline-events-for-an-issue
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:57:in `block in call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/response.rb:42:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:56:in `call'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/middleware/quota.rb:41:in `call'
	/usr/local/bundle/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/rack_builder.rb:152:in `build_response'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:444:in `run_request'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:200:in `get'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:84:in `paginate'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/issues.rb:321:in `issue_timeline'
	/usr/local/bundle/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/usr/local/bundle/gems/decoor-0.0.1/lib/decoor.rb:43:in `method_missing'
	/action/judges/label-was-attached/label-was-attached.rb:36:in `block (2 levels) in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/iterate.rb:109:in `block (2 levels) in over'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/iterate.rb:88:in `each'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/iterate.rb:88:in `block in over'
	<internal:kernel>:187:in `loop'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/iterate.rb:87:in `over'
	/action/judges/label-was-attached/label-was-attached.rb:35:in `block in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/iterate.rb:33:in `instance_eval'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/iterate.rb:33:in `iterate'
	/action/judges/label-was-attached/label-was-attached.rb:30:in `<top (required)>'
```

I believe, we fixed this problem in #218, but apparently not.

**Comment by yegor256** [comment]
@Suban05 maybe you can help?

**Comment by Suban05** [comment]
@yegor256 yes, of course

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.41`
