### ISSUE TITLE
empty repository causes runtime exception at `quantity-of-deliverables.rb`

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#254]
When Git repository is empty (has no commits), I [see](https://github.com/objectionary/eo/actions/runs/10329515167/job/28597406025) this:

```
Octokit::Conflict: GET https://api.github.com/repos/objectionary/hone-maven-plugin/commits?per_page=100&since=2024-07-13T06%3A28%3A18%2B00%3A00: 409 - Git Repository is empty. // See: https://docs.github.com/rest/commits/commits#list-commits
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:57:in `block in call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/response.rb:42:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:56:in `call'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/middleware/quota.rb:41:in `call'
	/usr/local/bundle/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/rack_builder.rb:152:in `build_response'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:444:in `run_request'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:200:in `get'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:84:in `paginate'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/commits.rb:27:in `commits'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/commits.rb:54:in `commits_since'
	/usr/local/bundle/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/usr/local/bundle/gems/decoor-0.0.1/lib/decoor.rb:43:in `method_missing'
	/action/judges/quantity-of-deliverables/quantity-of-deliverables.rb:52:in `block in <top (required)>'
```

Let's try to prevent this from happening somehow. Maybe let's check the number of commits first, through `Fbe.octo.repository()` call?

**Comment by Suban05** [comment]
@yegor256 May I take this one?

**Comment by yegor256** [comment]
@Suban05 please, go ahead

**Comment by Suban05** [comment]
@yegor256 unfortunately, we can't check the number of commits through `Fbe.octo.repository()` call. There is no information about it in the response(
I suggest just catching the exception using `rescue Octokit::Conflict`

**Comment by yegor256** [comment]
@Suban05 maybe GraphQL can help us?

**Comment by Yegorov** [comment]
@Suban05 For check empty repo we can use [size property](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository)
![size in empty repo](https://github.com/user-attachments/assets/d536bc8f-d96e-43c0-a6db-5d9348ec95ac)

Example:
```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  'https://api.github.com/repos/Yegorov/empty-repo'
```

```
{
  "id": 841899997,
  "node_id": "R_kgDOMi5f3Q",
  "name": "empty-repo",
  "full_name": "Yegorov/empty-repo",
  "private": false,
  "owner": {
    "login": "Yegorov",
    "id": 2566462,
    "node_id": "MDQ6VXNlcjI1NjY0NjI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2566462?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Yegorov",
    "html_url": "https://github.com/Yegorov",
    "followers_url": "https://api.github.com/users/Yegorov/followers",
    "following_url": "https://api.github.com/users/Yegorov/following{/other_user}",
    "gists_url": "https://api.github.com/users/Yegorov/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Yegorov/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Yegorov/subscriptions",
    "organizations_url": "https://api.github.com/users/Yegorov/orgs",
    "repos_url": "https://api.github.com/users/Yegorov/repos",
    "events_url": "https://api.github.com/users/Yegorov/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Yegorov/received_events",
    "type": "User",
    "site_admin": false
  },
  "html_url": "https://github.com/Yegorov/empty-repo",
  "description": null,
  "fork": false,
  "url": "https://api.github.com/repos/Yegorov/empty-repo",
  "forks_url": "https://api.github.com/repos/Yegorov/empty-repo/forks",
  "keys_url": "https://api.github.com/repos/Yegorov/empty-repo/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/Yegorov/empty-repo/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/Yegorov/empty-repo/teams",
  "hooks_url": "https://api.github.com/repos/Yegorov/empty-repo/hooks",
  "issue_events_url": "https://api.github.com/repos/Yegorov/empty-repo/issues/events{/number}",
  "events_url": "https://api.github.com/repos/Yegorov/empty-repo/events",
  "assignees_url": "https://api.github.com/repos/Yegorov/empty-repo/assignees{/user}",
  "branches_url": "https://api.github.com/repos/Yegorov/empty-repo/branches{/branch}",
  "tags_url": "https://api.github.com/repos/Yegorov/empty-repo/tags",
  "blobs_url": "https://api.github.com/repos/Yegorov/empty-repo/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/Yegorov/empty-repo/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/Yegorov/empty-repo/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/Yegorov/empty-repo/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/Yegorov/empty-repo/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/Yegorov/empty-repo/languages",
  "stargazers_url": "https://api.github.com/repos/Yegorov/empty-repo/stargazers",
  "contributors_url": "https://api.github.com/repos/Yegorov/empty-repo/contributors",
  "subscribers_url": "https://api.github.com/repos/Yegorov/empty-repo/subscribers",
  "subscription_url": "https://api.github.com/repos/Yegorov/empty-repo/subscription",
  "commits_url": "https://api.github.com/repos/Yegorov/empty-repo/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/Yegorov/empty-repo/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/Yegorov/empty-repo/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/Yegorov/empty-repo/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/Yegorov/empty-repo/contents/{+path}",
  "compare_url": "https://api.github.com/repos/Yegorov/empty-repo/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/Yegorov/empty-repo/merges",
  "archive_url": "https://api.github.com/repos/Yegorov/empty-repo/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/Yegorov/empty-repo/downloads",
  "issues_url": "https://api.github.com/repos/Yegorov/empty-repo/issues{/number}",
  "pulls_url": "https://api.github.com/repos/Yegorov/empty-repo/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/Yegorov/empty-repo/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/Yegorov/empty-repo/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/Yegorov/empty-repo/labels{/name}",
  "releases_url": "https://api.github.com/repos/Yegorov/empty-repo/releases{/id}",
  "deployments_url": "https://api.github.com/repos/Yegorov/empty-repo/deployments",
  "created_at": "2024-08-13T09:14:34Z",
  "updated_at": "2024-08-13T09:14:34Z",
  "pushed_at": "2024-08-13T09:14:34Z",
  "git_url": "git://github.com/Yegorov/empty-repo.git",
  "ssh_url": "git@github.com:Yegorov/empty-repo.git",
  "clone_url": "https://github.com/Yegorov/empty-repo.git",
  "svn_url": "https://github.com/Yegorov/empty-repo",
  "homepage": null,
  "size": 0,
  "stargazers_count": 0,
  "watchers_count": 0,
  "language": null,
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "has_discussions": false,
  "forks_count": 0,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 0,
  "license": null,
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [

  ],
  "visibility": "public",
  "forks": 0,
  "open_issues": 0,
  "watchers": 0,
  "default_branch": "main",
  "temp_clone_token": null,
  "network_count": 0,
  "subscribers_count": 1
}
```

**Comment by Suban05** [comment]
@Yegorov thanks, you are right
