### ISSUE TITLE
`NoMethodError: undefined method `[]' for nil` in `github-events.rb`

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#325]
I found it [here](https://github.com/zerocracy/judges-action/actions/runs/10698546946/job/29658188088):

```
D: Found 40 fact(s) by '(and (eq repository 799113787) (eq what 'release-published'))' in 25ms
D: Octokit::Client.compare("yegor256/judges", "0.26.0", "0.26.1") in 439ms
NoMethodError: undefined method `[]' for nil
	/action/judges/github-events/github-events.rb:52:in `block in fetch_contributors'
	/action/judges/github-events/github-events.rb:51:in `each'
	/action/judges/github-events/github-events.rb:51:in `fetch_contributors'
	/action/judges/github-events/github-events.rb:265:in `fill_up_event'
	/action/judges/github-events/github-events.rb:319:in `block (4 levels) in <top (required)>'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:65:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:73:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase.rb:168:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:72:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/pre.rb:62:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:63:in `txn'
	/action/judges/github-events/github-events.rb:310:in `block (3 levels) in <top (required)>'
	/action/judges/github-events/github-events.rb:298:in `each'
	/action/judges/github-events/github-events.rb:298:in `each_with_index'
	/action/judges/github-events/github-events.rb:298:in `block (2 levels) in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.61/lib/fbe/iterate.rb:109:in `block (2 levels) in over'
	/usr/local/bundle/gems/fbe-0.0.61/lib/fbe/iterate.rb:88:in `each'
	/usr/local/bundle/gems/fbe-0.0.61/lib/fbe/iterate.rb:88:in `block in over'
```

**Comment by Yegorov** [comment]
@yegor256 can i try fix it?

**Comment by yegor256** [comment]
@Yegorov sure, please go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.51`
