### ISSUE TITLE
`NoMethodError: undefined method - for nil` in the `quality-of-service.rb`

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#338]
I found this [here](https://github.com/zerocracy/judges-action/actions/runs/10884491018/job/30199895449):

```
NoMethodError: undefined method `-' for nil
	/action/judges/quality-of-service/quality-of-service.rb:138:in `block (3 levels) in <top (required)>'
	/action/judges/quality-of-service/quality-of-service.rb:135:in `each'
	/action/judges/quality-of-service/quality-of-service.rb:135:in `block (2 levels) in <top (required)>'
	/action/judges/quality-of-service/quality-of-service.rb:132:in `each'
	/action/judges/quality-of-service/quality-of-service.rb:132:in `block in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.65/lib/fbe/regularly.rb:55:in `regularly'
	/action/judges/quality-of-service/quality-of-service.rb:30:in `<top (required)>'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judge.rb:60:in `load'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judge.rb:60:in `block in run'
	/usr/local/bundle/gems/elapsed-0.0.1/lib/elapsed.rb:45:in `elapsed'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judge.rb:59:in `run'
```

**Comment by Yegorov** [comment]
@yegor256 can i try fix it?

**Comment by yegor256** [comment]
@Yegorov please, go ahead
