### ISSUE TITLE
`User not found` leads to runtime exception

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#341]
I found this problem [here](https://github.com/zerocracy/judges-action/actions/runs/10900854041/job/30249395419):

```
Octokit::Forbidden: GET https://api.github.com/user/29139614: 403 - Resource not accessible by integration // See: https://docs.github.com/rest
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:57:in `block in call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/response.rb:42:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:56:in `call'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/usr/local/bundle/gems/fbe-0.0.53/lib/fbe/middleware/quota.rb:48:in `call'
	/usr/local/bundle/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/rack_builder.rb:152:in `build_response'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:444:in `run_request'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:200:in `get'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:[99](https://github.com/zerocracy/judges-action/actions/runs/10900854041/job/30249395419#step:6:100):in `call'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:19:in `get'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/users.rb:34:in `user'
	/usr/local/bundle/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/usr/local/bundle/gems/fbe-0.0.53/lib/fbe/octo.rb:115:in `user_name_by_id'
	/home/judges/add-user-names/add-user-names.rb:31:in `block (2 levels) in <top (required)>'Octokit::Forbidden: GET https://api.github.com/user/29139614: 403 - Resource not accessible by integration // See: https://docs.github.com/rest
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:57:in `block in call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/response.rb:42:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:56:in `call'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/usr/local/bundle/gems/fbe-0.0.53/lib/fbe/middleware/quota.rb:48:in `call'
	/usr/local/bundle/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/rack_builder.rb:152:in `build_response'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:444:in `run_request'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:200:in `get'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:[99](https://github.com/zerocracy/judges-action/actions/runs/10900854041/job/30249395419#step:6:100):in `call'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:19:in `get'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/users.rb:34:in `user'
	/usr/local/bundle/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/usr/local/bundle/gems/fbe-0.0.53/lib/fbe/octo.rb:115:in `user_name_by_id'
	/home/judges/add-user-names/add-user-names.rb:31:in `block (2 levels) in <top (required)>'
```

Probably, the user is deleted and that's why we fail.

**Comment by Yegorov** [comment]
@yegor256 As I see this error refers to [this project](https://github.com/zerocracy/pages-action), see this line: 
```
/home/judges/add-user-names/add-user-names.rb:31:in `block (2 levels) in <top (required)>'Octokit::Forbidden
```
Maybe this issue needs to be transferred to that project?
If I understand it correctly, then it is necessary to ignore [`Octokit::ClientError`](https://github.com/octokit/octokit.rb/blob/71e3d209400ff29440d87581db90314b6272355b/lib/octokit/error.rb#L265) exception [here](https://github.com/zerocracy/pages-action/blob/86a26554196fac19d1391f90b121401763e0a62b/judges/add-user-names/add-user-names.rb#L31)
Can i fix it?
