### ISSUE TITLE
NoMethodError: undefined method `[]' for nil

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#350]
I found it [here](https://github.com/zerocracy/judges-action/actions/runs/11005314143/job/30557758445):

```
D: Octokit::Client.pull_request_comments("zerocracy/judges-action", 349) in 142ms
D: Octokit::Client.issue_comments("zerocracy/judges-action", 349) in 160ms
D: Octokit::Client.issue_comment_reactions("zerocracy/judges-action", 23693[304](https://github.com/zerocracy/judges-action/actions/runs/11005314143/job/30557758445#step:5:305)00) in 136ms
D: Octokit::Client.issue_comment_reactions("zerocracy/judges-action", 2369334861) in 149ms
D: Octokit::Client.issue_comment_reactions("zerocracy/judges-action", 2369423760) in 167ms
NoMethodError: undefined method `[]' for nil
	/action/judges/github-events/github-events.rb:97:in `comments_info'
	/action/judges/github-events/github-events.rb:191:in `fill_up_event'
	/action/judges/github-events/github-events.rb:320:in `block (4 levels) in <top (required)>'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:65:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:73:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase.rb:168:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:72:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/pre.rb:62:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:63:in `txn'
	/action/judges/github-events/github-events.rb:[311](https://github.com/zerocracy/judges-action/actions/runs/11005314143/job/30557758445#step:5:312):in `block (3 levels) in <top (required)>'
	/action/judges/github-events/github-events.rb:299:in `each'
	/action/judges/github-events/github-events.rb:299:in `each_with_index'
	/action/judges/github-events/github-events.rb:299:in `block (2 levels) in <top (required)>'
```

**Comment by Suban05** [comment]
@yegor256 I can help

**Comment by yegor256** [comment]
@Suban05 ok, it's yours

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.53`
