### ISSUE TITLE
RuntimeError: Can't find 'tag' attribute out of ...

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#373]
I found it [here](https://github.com/objectionary/eo/actions/runs/11177233856/job/31072299243):

```
RuntimeError: Can't find 'tag' attribute out of [_id, _time, _version, where, event_id, when, event_type, repository, who, release_id, what, details, is_human]
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/fact.rb:90:in `block in <class:Fact>'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/tee.rb:54:in `block in <class:Tee>'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/accum.rb:66:in `block in <class:Accum>'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:101:in `block in <class:Fact>'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/action/judges/github-events/github-events.rb:51:in `fetch_contributors'
```

**Comment by Yegorov** [comment]
@yegor256 may I try this one?

**Comment by yegor256** [comment]
@Yegorov please, go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.54`
