### ISSUE TITLE
TypeError: can't convert NilClass into an exact number

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#375]
I found it [here](https://github.com/zerocracy/judges-action/actions/runs/11196224163/job/31124823046):

```
D: Found 1 fact(s) by '(and (eq where 'github') (eq repository 1396) (eq issue 42) (eq what 'label-was-attached') (exists when) (or (eq label 'bug') (eq label 'enhancement')))' in 249μs
TypeError: can't convert NilClass into an exact number
	/action/judges/quality-of-service/quality-of-service.rb:189:in `-'
	/action/judges/quality-of-service/quality-of-service.rb:189:in `block (3 levels) in <top (required)>'
	/action/judges/quality-of-service/quality-of-service.rb:173:in `each'
	/action/judges/quality-of-service/quality-of-service.rb:173:in `block (2 levels) in <top (required)>'
	/action/judges/quality-of-service/quality-of-service.rb:172:in `each'
	/action/judges/quality-of-service/quality-of-service.rb:172:in `block in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.74/lib/fbe/regularly.rb:55:in `regularly'
	/action/judges/quality-of-service/quality-of-service.rb:30:in `<top (required)>'
```

**Comment by Yegorov** [comment]
@yegor256 may I try this one?

**Comment by yegor256** [comment]
@Yegorov sure, please go ahead
