### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#397]
I found it [here](https://github.com/objectionary/eo/actions/runs/11489045273/job/31977054048):

```
TypeError: no implicit conversion of Symbol into Integer
	/action/judges/github-events/github-events.rb:68:in `block in fetch_contributors'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/resource.rb:128:in `each'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/resource.rb:128:in `each'
	/action/judges/github-events/github-events.rb:67:in `fetch_contributors'
	/action/judges/github-events/github-events.rb:278:in `fill_up_event'
	/action/judges/github-events/github-events.rb:332:in `block (4 levels) in <top (required)>'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:65:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:73:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase.rb:168:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:72:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/pre.rb:62:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:63:in `txn'
	/action/judges/github-events/github-events.rb:323:in `block (3 levels) in <top (required)>'
	/action/judges/github-events/github-events.rb:311:in `each'
	/action/judges/github-events/github-events.rb:311:in `each_with_index'
	/action/judges/github-events/github-events.rb:311:in `block (2 levels) in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.76/lib/fbe/iterate.rb:109:in `block (2 levels) in over'
	/usr/local/bundle/gems/fbe-0.0.76/lib/fbe/iterate.rb:88:in `each'
	/usr/local/bundle/gems/fbe-0.0.76/lib/fbe/iterate.rb:88:in `block in over']()
```

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov yes, please
